name: Release Collect Service to Docker Hub arm64v8

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/collect-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/${{ github.event.repository.name }}-collect-service:latest
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

